### PR TITLE
feat: Add 'unzip' option

### PR DESCRIPTION
**Pull request by gjobin**
The 'unzip' option will unzip each record before printing it to the console.

### CODE REVIEW

**Comment by gjobin** [comment]
Somehow piping to `gzip -d` does not work giving `gzip: unknown compression
format`. I had the same result copy/pasting the console output into a file
or a variable because (I Think) some control characters used in the zip
compression moves the "cursor" at beginning of the line and overwrites some
data on the output, rendering it invalid. Note that I am not 100% sure it's
the same reason for

I do not expect kafka-console-consumer to have a --unzip feature because
they implemented it in the protocol itself, if the producer enables any
compression, the clients will know to decompress automatically. Kinesis
streams does not support such feature, at least on all that i've found
online. People do compress and decompress in their producing/consuming
apps. GZIP i one of the supported Kafka compression scheme and is pretty
common/popular. It also supports a few other compression algorithms.

As much as I'd like to see this PR merged, I understand your concerns.
Also, if there's a way to have this work with a pipe function, I'd be happy
to use it.

Thanks for looking at it.

Guillaume Jobin

**Comment by gjobin** [comment]
Hi Chris,

I like your thinking.
Thanks for merging,

Guillaume Jobin

**Comment by crccheck** [comment]
I was trying to update some other dependencies before doing a deploy but ran into some problems. I guess I'll just deploy this change without those updates.

**Comment by crccheck** [comment]
haha I'm so stupid. There's another PR that does auto-unzipping #39. Now that I think about it, this isn't a production reading library, so performance isn't important and magically uncompressing is an option.

**Comment by gjobin** [comment]
That's nice.
I prefer the control of passing an argument however as you otherwise won't
know that the data is compressed or not using the tool.

Guillaume Jobin

**Pull request merged**
